config/routes.rb
OneWayAir::Application.routes.draw do

  resources :reservations

  get '/flights' => 'flights#index'

  post '/reservations', controller: 'reservations', action: 'create'

  # def dispatch()
  #  x = ReservationsController.new
  #  x.create
  # end
  get "/login" => 'sessions#new', as: :login

  post "sessions/create" => 'sessions#create', as: :create_session

  get "/logout" => 'sessions#destroy', as: :logout

  resources :users


  root :to => 'flights#index'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrival_airport, :departs_at, :departure_airport, :miles, :number, :seats

  before_create :calculates_miles

  belongs_to :departure_airport, :class_name => 'Airport'
  belongs_to :arrival_airport, :class_name => 'Airport'

  MILEAGE_CHART = [
            ['ORD', 'JFK', 740],
            ['ORD', 'LAX', 1744],
            ['ORD', 'SFO', 1846],
            ['JFK', 'LAX', 2475],
            ['JFK', 'SFO', 2586],
            ['LAX', 'SFO', 338]
          ]

  def calculates_miles
    e = MILEAGE_CHART.detect do |entry|
      (entry.first == self.departure_airport.code &&
            entry.second == self.arrival_airport.code) ||
      (entry.second == self.departure_airport.code &&
            entry.first == self.arrival_airport.code)
    end
    self.miles = e.third
  end

  def arrives_at
    departs_at + duration.minutes
  end

  def duration
    miles / 8
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    if params[:keyword].present?
      keyword = params[:keyword]
      airports = Airport.where('code LIKE ? OR city LIKE ?', "%#{keyword}%", "%#{keyword}%")

      @flights = Flight.where('departure_airport_id IN (?)', airports)

      # @flights = Flight.where("departure_airport LIKE ? or arrival_airport LIKE ?",
      #                           "%#{keyword}%",
      #                           "%#{keyword}%")
      @flights = @flights.order('number asc')
    else
      @flights = Flight.order('number asc')
    end

    @flights = @flights.paginate(:page => params[:page], :per_page => 5)

  end

end

app/views/flights/_flight.html.erb
<tr>
  <td><%= flight.number %></td>
  <td><%= flight.departure_airport.city %></td>
  <td><%= flight.departs_at.localtime.strftime("%l:%M %p %Z") %></td>
  <td><%= flight.arrival_airport.city %></td>
  <td><%#= flight.arrives_at.localtime.strftime("%l:%M %p %Z") %></td>
  <td><%= flight.miles %></td>
  <td><%= flight.duration %> minutes</td>
  <td><%= flight.seats %></td>
  <td><%= link_to "Book Now", new_reservation_url(flight_id: flight.id), class: 'btn btn-success' %></td>
</tr>

app/views/flights/_schedule.html.erb
<tbody>
  <%= render @flights %>
</tbody>

app/views/flights/_table_top.html.erb
<thead>
  <tr>
    <th>Flight #</th>
    <th>From</th>
    <th>Departs</th>
    <th>To</th>
    <th>Arrives</th>
    <th>Miles</th>
    <th>Duration</th>
    <th>Seats</th>
    <th></th>
  </tr>
</thead>

app/views/flights/index.html.erb
<div class="row">
  <div class="span12">
    <h1 class="page-header">Today's Flight Schedule</h1>

    <%= will_paginate @flights %>

    <table class="table table-hover">
      <%= render 'table_top' %>
      <%= render 'schedule' %>
    </table>
  </div>
</div>