config/routes.rb
OneWayAir::Application.routes.draw do

  resources :reservations

  get '/flights' => 'flights#index'

  post '/reservations', controller: 'reservations', action: 'create'

  # def dispatch()
  #  x = ReservationsController.new
  #  x.create
  # end
  get "/login" => 'sessions#new', as: :login

  post "sessions/create" => 'sessions#create', as: :create_session

  get "/logout" => 'sessions#destroy', as: :logout

  resources :users


  root :to => 'flights#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :email

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :reservations
  has_many :flights, through: :reservations

  has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, except: [:new, :create, :index]
  before_filter :authorize_user, except: [:new, :create]

  def find_user
    @user = User.find_by_id(params[:id])
  end

  def authorize_user
    logger.info "session[:user_id] = #{session[:user_id]}"
    logger.info "session[:user_id].class = #{session[:user_id].class}"
    logger.info "params[:user_id] = #{params[:id]}"
    logger.info "params[:user_id].class = #{params[:id].class}"
    if session[:user_id].to_s != params[:id]
      redirect_to root_url, notice: "Nice try!"
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="row">
  <div class="span12">
    <h1 class="page-header">My Profile</h1>
    <h2>Total Miles Earned: <%= @user.miles %></h2>
    <h2>Reservations</h2>
    <ul>
      <% @user.reservations.each do |reservation| %>
      <li><%= link_to "Flight ##{reservation.flight.number} #{reservation.departs_on} #{reservation.flight.departure_airport}-#{reservation.flight.arrival_airport} #{reservation.flight.departs_at.strftime("%l:%M %p")} - #{reservation.flight.arrives_at.strftime("%l:%M %p")}", reservation_url(reservation) %></li>
      <% end %>
    </ul>
  </div>
</div>