config/routes.rb
OneWayAir::Application.routes.draw do

  resources :reservations

  get '/flights' => 'flights#index'

  post '/reservations', controller: 'reservations', action: 'create'

  # def dispatch()
  #  x = ReservationsController.new
  #  x.create
  # end
  get "/login" => 'sessions#new', as: :login

  post "sessions/create" => 'sessions#create', as: :create_session

  get "/logout" => 'sessions#destroy', as: :logout

  resources :users


  root :to => 'flights#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :credit_card, :departs_on, :flight_id, :user_id

  belongs_to :flight
  belongs_to :user

  after_create :increase_user_miles

  validate :credit_card_is_a_visa

  def credit_card_is_a_visa
    unless credit_card.starts_with?("4") && self.credit_card.length == 16
      errors.add(:credit_card, "must be a Visa card")
    end
  end

  # def user
  #   # memoization
  #   @user ||= User.find_by_id(self.user_id)

  #   # @user = @user || User.find_by_id(self.user_id)

  #   # if @user.nil?
  #   #   @user = User.find_by_id(self.user_id)
  #   # end
  #   # return @user
  # end

  def increase_user_miles
    self.user.miles += self.flight.miles
    self.user.save
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_filter :authorize_user

  def authorize_user
    if session[:user_id].blank?
      redirect_to root_url, notice: "Please login first."
    end
  end

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new(flight_id: params[:flight_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])
    @reservation.user_id = session[:user_id]

    respond_to do |format|
      if @reservation.save
        ReservationMailer.confirm(@reservation).deliver

        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :flight_id %>

  <div class="field">
    <%= f.label :departs_on %><br />
    <%= f.date_select :departs_on %>
  </div>
  <div class="field">
    <%= f.label :credit_card %><br />
    <%= f.text_field :credit_card %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Flight</th>
    <th>User</th>
    <th>Departs on</th>
    <th>Credit card</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.flight_id %></td>
    <td><%= reservation.user_id %></td>
    <td><%= reservation.departs_on %></td>
    <td><%= reservation.credit_card %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p>
  <b>Flight:</b>
  #<%= @reservation.flight.number %>
</p>


<p>
  <b>Departs on:</b>
  <%= @reservation.departs_on %>
</p>

<p>
  <b>Credit card:</b>
  <%= @reservation.credit_card %>
</p>