config/routes.rb
OneWayAir::Application.routes.draw do

  resources :reservations

  get '/flights' => 'flights#index'

  post '/reservations', controller: 'reservations', action: 'create'

  # def dispatch()
  #  x = ReservationsController.new
  #  x.create
  # end
  get "/login" => 'sessions#new', as: :login

  post "sessions/create" => 'sessions#create', as: :create_session

  get "/logout" => 'sessions#destroy', as: :logout

  resources :users


  root :to => 'flights#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneWayAir</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <title>OneWay Airlines</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le styles -->
  <!-- <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet"> -->

  <style type="text/css">
    body { padding-top: 60px; padding-bottom: 40px; }
  </style>

  <style type="text/css">
    .table thead th { font-size: 20px; background: #5484a7; color: white; text-align: center; height: 30px; padding: 12px; vertical-align: middle}
    .table td { text-align: center; }
  </style>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Le fav and touch icons -->
  <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/images/favicon.ico">
  <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-114x114.png">
</head>
<body>


  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand span2" href="/">OneWay Airlines</a>
        <div class="nav-collapse">
          <form class="navbar-search pull-left" action="/flights" method="get">
            <input type="text" class="search-query span3" placeholder="Search by city or airport code" name="keyword">
          </form>
          <ul class="nav pull-right">
            <li><a href="/airports.html">Cities</a></li>
            <li><a href="/support.html">Customer Support</a></li>
            <% if session[:user_id] %>
              <li><a href="/logout">Logout</a></li>
              <li><%= link_to "My Profile", user_url(session[:user_id]) %></li>

            <% else -%>
              <li><a href="/login">Login</a></li>
              <li><a href="/users/new">Sign up</a></li>
            <% end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <%= notice %>
  <div class="container">
    <%= yield %>

    <hr>

    <footer>
      <p>&copy;2013 OneWay Airlines.  Got a comment or suggestion?  Keep it to yourself!</p>
    </footer>
  </div> <!-- /container -->

</body>
</html>